/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.osacky.replace.example

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'com.osacky.replace.com.osacky.replace.example.greeting' plugin.
 */
class ReplacePluginTaskPluginFunctionalTest {
  @Test
  fun `can run task`() {
    // Setup the test build
    val projectDir = File("build/functionalTest")
    projectDir.mkdirs()
    projectDir.resolve("settings.gradle").writeText("")
    projectDir.resolve("build.gradle").writeText(
      """
            plugins {
                id('com.osacky.incompatible')
            }
        """
    )

    // Run the build
    val runner = GradleRunner.create()
      .forwardOutput()
      .withPluginClasspath()
      .withArguments("incompatibleTask")
      .withProjectDir(projectDir)
    val result = runner.build();

    // Verify the result
    assertTrue(result.output.contains("foo is running"))
  }
}
